# Commands to be performed on player's death
CommandsOnDeath:
  Command1: ""
  Command2: ""

#Commands to be performed when the player has no more lives left
CommandsNoMoreLives:
  Command1: ""
  Command2: ""

# Base amount for starting lives and maximum lives
Lives:
  MaxLives: 100
  StartingAmount: 10
  Penalty: 1

# Database parameters
database:
  database: "SkyblockIslandLife"
  url: "localhost"
  port: 3306
  user: "root"
  password: ""

