# Commands to be performed on player's death
CommandsOnDeath:
  Command1: "msg %player% Vous avez %islandlife_left% vie(s) restante(s) !"

#Commands to be performed when the player has no more lives left
CommandsNoMoreLives:

# Base amount for starting lives and maximum lives
Lives:
  MaxLives: 100
  StartingAmount: 10
  Penalty: 1

# Database parameters
database:
  database: "SkyblockIslandLife"
  prefix: "skylife_"
  url: "localhost"
  port: 3306
  user: "root"
  password: ""

