name: SkyblockIslandLife
version: '${project.version}'
main: fr.nono74210.skyblockislandlife.SkyblockIslandLife
api-version: '1.20'
depend:
  - "PlaceholderAPI"
  - "SuperiorSkyblock2"
commands:
  vie:
    description: Base command for the plugin
    permission: vie.seen
permissions:
  vie.seen:
    description: Allows one to see their amount of lives left
  vie.reload:
    description: Allows one to reload plugin's config
    default: op
  vie.add:
    description: Allows one to add lives to a specified player
    default: op
  vie.help:
    description: Allows one to see available commands
    default: op