name: SkblockIslandLife
version: '${project.version}'
main: fr.nono74210.skyblockislandlife.SkyblockIslandLife
api-version: '1.20'
depend:
  - "PlaceholderAPI"
  - "SuperiorSkyblock2"
commands:
  vie:
    description: Commande de base du plugin
    permission: vie.seen
permissions:
  vie.seen:
    description: Permet de voir son nombre de vies restantes
  vie.reload:
    description: Permet de reload la config du plugin
    default: op
  vie.add:
    description: Permet d'ajouter des vies à une ile
    default: op
